language: node_js
node_js:
  - '10'

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - commitlint-travis
        - yarn test

    - stage: deploy
      script:
        - yarn build
        - yarn semantic-release
        - yarn deploy:documentation

cache: yarn
